"""Доменные модели — единая структура клиентской базы."""

from app.domain.models import (
    Campaign,
    CampaignStatus,
    Customer,
    Gender,
    ImportantDate,
    ImportantDateSource,
    Interaction,
    InteractionChannel,
    Lead,
    LeadStatus,
    Order,
    OrderItem,
    PreferenceOwner,
    PreferenceProfile,
    Recipient,
    Recommendation,
    Segment,
    SegmentOrigin,
    SourceType,
    normalize_phone,
)

__all__ = [
    "Campaign",
    "CampaignStatus",
    "Customer",
    "Gender",
    "ImportantDate",
    "ImportantDateSource",
    "Interaction",
    "InteractionChannel",
    "Lead",
    "LeadStatus",
    "Order",
    "OrderItem",
    "PreferenceOwner",
    "PreferenceProfile",
    "Recipient",
    "Recommendation",
    "Segment",
    "SegmentOrigin",
    "SourceType",
    "normalize_phone",
]
